import { AuthContextProvider } from './context/AuthContext'
import './globals.css'

export const metadata = {
	title: 'fastjobs.io',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<AuthContextProvider>
				<body>{children}</body>
			</AuthContextProvider>
		</html>
	)
}
